- controller/Monitor.php
- manifest.php
- model/LtiListenerService.php
- model/delivery/ProctorService.php
- scripts/update/Updater.php
- views/js/controller/delegate.js
https://oat-sa.atlassian.net/browse/TAO-3790
depends 
https://github.com/oat-sa/extension-tao-proctoring/pull/282
> Tao 3790/custom tags

- manifest.php
- model/execution/LtiDeliveryExecutionService.php
- scripts/update/Updater.php
requires https://github.com/oat-sa/extension-tao-ltideliveryprovider/pull/73
> implement LtiDeliveryExecutionService::getLinkedDeliveryExecutions()

- manifest.php
- model/LtiListenerService.php
- scripts/update/Updater.php
requires https://github.com/oat-sa/extension-tao-lti/pull/64
> Catch missing data on LTI call

- controller/SimplePageModule.php
- manifest.php
- scripts/update/Updater.php
Story: https://oat-sa.atlassian.net/browse/TAO-4254
Depends on https://github.com/oat-sa/tao-core/pull/1320 and https://github.com/oat-sa/extension-tao-proctoring/pull/370
> Inject redirect url form LTI data

- manifest.php
- model/delivery/ProctorService.php
- scripts/install/SetupTestRunnerMessageService.php
- scripts/update/Updater.php
> Release 3.4.2

- manifest.php
- model/ActivityMonitoringService.php
- scripts/install/RegisterServices.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/extension-tao-proctoring/pull/515
> Custom metric added to operation screen - login queue length

- controller/SimplePageModule.php
- manifest.php
- scripts/update/Updater.php
> Release 3.6.0

- composer.json
- manifest.php
- scripts/update/Updater.php
> Release 3.6.1

- manifest.php
- model/LtiListenerService.php
- scripts/update/Updater.php
We store only custom lti paremeters.
For support purposes it is useful to store all the lti parameters.
> Act 106 log all lti parameters

- manifest.php
- model/execution/LtiDeliveryExecutionService.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/extension-tao-ltideliveryprovider/pull/152
> Remove LtiDeliveryExecutionService::isFinished method

- composer.json
- manifest.php
- scripts/update/Updater.php
> Release 4.0.1

- manifest.php
- model/ActivityMonitoringService.php
- scripts/update/Updater.php
Depends on https://github.com/oat-sa/tao-core/pull/1841
> Fix/tao 6986/login queue active flag

- manifest.php
- scripts/update/Updater.php
bumped version according to the changes in the requires of the manifest.php
> fixed extension version

- config/default/LtiMonitorParameters.conf.php
- controller/Monitor.php
- manifest.php
- model/LtiMonitorParametersService.php
- scripts/update/Updater.php
- test/unit/model/LtiMonitorParametersServiceTest.php
Pull request summary
https://oat-sa.atlassian.net/browse/ACTP-221
Added service to make monitoring params configurable
Proctoring page should work as expected (as worked before)
Companion PR :
> created lti monitor parameters service

- manifest.php
- model/delivery/LtiTestTakerAuthorizationService.php
- scripts/update/Updater.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
Please verify the following points :
> Release 7.0.0

- manifest.php
- scripts/update/Updater.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
> Feature/tdr 1/phpunit8 upgrade

- manifest.php
- model/ActivityMonitoringService.php
- scripts/update/Updater.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
Please verify the following points :
> Release 8.0.0

- manifest.php
- model/LtiLaunchDataService.php
- model/LtiResultCustomFieldsService.php
- scripts/install/RegisterServices.php
- scripts/update/Updater.php
- test/unit/model/LtiLaunchDataServiceTest.php
- test/unit/model/LtiResultCustomFieldsServiceTest.php
Related task: https://oat-sa.atlassian.net/browse/TDR-22
see: https://github.com/oat-sa/extension-tao-ltideliveryprovider/pull/244
> Fix/tdr 22/remove tao proctoring dependency

- controller/DeliveryServer.php
- manifest.php
Please verify the following points :
> Release 9.1.1

- composer.json
- manifest.php
> Release 10.0.0

- controller/DeliveryServer.php
- model/LtiLaunchDataService.php
- model/LtiListenerService.php
> Release 10.2.0

- composer.json
- model/delivery/LtiTestTakerAuthorizationService.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
> Release 10.3.0

- controller/DeliveryServer.php
- manifest.php
- model/ProctorServiceProvider.php
- model/delivery/AutoStartProctoredDeliveryService.php
- model/delivery/LtiTestTakerAuthorizationService.php
- test/unit/model/delivery/AutoStartProctoredDeliveryServiceTest.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
> Release 10.4.0

- model/delivery/AutoStartProctoredDeliveryService.php
Redirect to waiting page when test is paused
- fix: change the log message when the status is changed
> fix: change the log message when the status is changed

- model/delivery/AutoStartProctoredDeliveryService.php
> Release 10.4.1

- model/delivery/LtiTestTakerAuthorizationService.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
Details on how to test in the ticket
https://oat-sa.atlassian.net/browse/TR-3512
When launching the lti delivery execution with autostart, force the redirection to the proper ltiProctoring URL
> fix: force redirect user in case wrong LTI url

- model/delivery/LtiTestTakerAuthorizationService.php
- test/unit/model/delivery/LtiTestTakerAuthorizationServiceTest.php
> Release 10.4.2

- scripts/install/AlterDeliveryMonitoringTable.php
> Release 10.4.4

- model/LtiListenerService.php
> Release 10.5.1
